[package]
name = "hive"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
itertools = "0.10.3"
alloc_counter = "0.0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "board"
harness = false
